# Generated by Django 2.2 on 2020-06-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20200614_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
