# Generated by Django 2.2 on 2020-06-12 12:16

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=300, null=True, verbose_name='Product Name')),
                ('slug', models.SlugField(blank=True, max_length=350, null=True, unique=True)),
                ('maf_date', models.DateField(null=True, verbose_name='manufacturing_date')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('instock', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(null=True, on_delete='store_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['title', '-maf_date', '-created', '-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='product_category')),
                ('post', models.ManyToManyField(blank=True, to='product.Product')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['title'],
                'managed': True,
            },
        ),
    ]
