# Generated by Django 2.2 on 2020-06-14 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='owner',
            field=models.OneToOneField(null=True, on_delete='marchant', related_name='marchant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete='product_brand', related_name='product_brand', to='product.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete='store_name', to='product.Seller'),
        ),
    ]
