# Generated by Django 2.2 on 2020-06-15 04:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import shooze.product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200614_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=150, verbose_name='Product_image_title')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shooze.product.models.product_file_path, verbose_name='upload_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Product File',
                'verbose_name_plural': 'Product Files',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
