# Generated by Django 2.2 on 2020-06-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200612_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='title',
            field=models.CharField(max_length=300, null=True, verbose_name='Store Name'),
        ),
    ]
