# Generated by Django 2.2 on 2020-06-12 19:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import shooze.product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200612_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=300, null=True, verbose_name='Brand_Name')),
                ('slug', models.SlugField(blank=True, max_length=350, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=shooze.product.models.brand_logo, verbose_name='brand_logo')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='title',
            field=models.CharField(max_length=300, null=True, verbose_name='Store_Name'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('author', models.CharField(max_length=300, verbose_name='author')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete='review_product', related_name='reviewed_product', to='product.Product')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete='product_brand', related_name='product_brand', to='product.Brand'),
        ),
    ]
