# Generated by Django 2.2 on 2020-06-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200612_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='guest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='seller',
            field=models.BooleanField(default=False),
        ),
    ]
